image: alpine:latest

pages:
  stage: deploy
  script:
    - wget -qO public/calendar.ics https://calendar.google.com/calendar/ical/kimberly.zick%40gmail.com/public/basic.ics
  artifacts:
    paths:
      - public
  only:
    - master
